dataSources: []
dbt:
  projectDir: .
  # tag: 'piperider'

profiler:
#   table:
#     # the maximum row count to profile. (Default unlimited)
#     limit: 1000000
#     duplicateRows: false

telemetry:
  id: 700617a675244126bd2bd60730231d62
