[project]
name = ""
version = "1.0"
description = "Analytics Engineering with dbt, duckdb and piperider"
license = {text = "CC-BY-SA-4.0"}
readme = "README.md"
authors = [
    {name = "Bruno Oliveira", email = "bruno.ariev@gmail.com"},
]

requires-python = ">=3.10,<3.12"

dependencies = [
    "dbt-duckdb>=1.7.2,<2.0",
    "duckdb>=0.10.0,<1.0",
    "s3fs>=2024.2.0,<2024.3.0",
    "gcsfs>=2024.2.0,<2024.3.0",
    "piperider[duckdb]>=0.41.0,<1.0",
]

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.2.2",
]

[tool.ruff]
line-length = 100