x-airflow-image: &airflow-image apache/airflow:${AIRFLOW_VERSION:-2.10.4-python3.12}
x-postgres-image: &postgres-image postgres:${POSTGRES_VERSION:-17-alpine}
x-redis-image: &redis-image redis:${REDIS_VERSION:-7-alpine}

x-airflow-common:
  &airflow-common
  image: *airflow-image 
  user: "${AIRFLOW_UID:-50000}:0"
  environment:
    &airflow-common-env
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-metastore/airflow
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-metastore/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@airflow-redis:6379/0
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
  depends_on:
    airflow-metastore:
      condition: service_healthy
    airflow-redis:
      condition: service_healthy

services:
  ingest-db:
    image: *postgres-image
    container_name: ingest-db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'nyc_taxi'
    ports:
      - '5432:5432'
    volumes:
      - vol-ingest-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  airflow-metastore:
    image: *postgres-image
    container_name: airflow-metastore
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - '5432'
    volumes:
      - vol-airflow-metastore-celeryexec:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: on-failure

  airflow-redis:
    image: *redis-image
    container_name: airflow-redis
    ports:
      - '6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: on-failure

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: ["airflow", "scheduler"]
    ports:
      - '8974'
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8974/health"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: on-failure

  airflow-worker:
    <<: *airflow-common
    container_name: airflow-worker
    command: ["airflow", "celery", "worker"]
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 5s
      timeout: 10s
      retries: 5
    restart: on-failure

  airflow-triggerer:
    <<: *airflow-common
    container_name: airflow-triggerer
    command: ["airflow", "triggerer"]
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 5s
      timeout: 10s
      retries: 5
    restart: on-failure

  airflow-web:
    <<: *airflow-common
    container_name: airflow-web
    command: ["airflow", "webserver"]
    ports:
      - '8080:8080'
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: on-failure

  airflow-flower:
    <<: *airflow-common
    container_name: airflow-flower
    command: ["airflow", "celery", "flower", "--basic-auth=airflow:airflow"]
    ports:
      - '5555:5555'
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -u airflow:airflow http://localhost:5555"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: on-failure

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    user: "0:0"
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}:/sources

volumes:
  vol-ingest-db:
    name: vol-ingest-db
  vol-airflow-metastore-celeryexec:
    name: vol-airflow-metastore-celeryexec
