[project]
name = "airflow-playground"
version = "0.1"
description = "Workflow orchestration with Airflow"
readme = "README.md"
requires-python = ">=3.12,<3.13"

dependencies = [

]

[dependency-groups]
dev = [
    "ruff>=0.9.4",
]

[tool.ruff]
line-length = 100
lint.select = ["F", "E", "W", "I001"]