x-clickhouse-image: &clickhouse-image clickhouse/clickhouse-server:${CLICKHOUSE_VERSION:-24.9.2-alpine}
x-postgres-image: &postgres-image postgres:${POSTGRES_VERSION:-17-alpine}

services:
  clickhouse:
    image: *clickhouse-image
    container_name: clickhouse
    environment:
      CLICKHOUSE_DB: 'default'
      CLICKHOUSE_USER: 'clickhouse'
      CLICKHOUSE_PASSWORD: 'clickhouse'
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 0
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - dbt_ch_data:/var/lib/clickhouse/
      - dbt_ch_logs:/var/log/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8123/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: on-failure

  postgres:
    image: *postgres-image
    container_name: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'nyc_taxi'
    ports:
      - '5432:5432'
    volumes:
      - dbt_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: on-failure

volumes:
  dbt_ch_data:
    name: dbt_clickhouse_data
  dbt_ch_logs:
    name: dbt_clickhouse_logs
  dbt_pg_data:
    name: dbt_pg_data
