x-postgres-image: &postgres-image postgres:${POSTGRES_VERSION:-16-alpine}

services:
  postgres:
    image: *postgres-image
    container_name: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'nyc_taxi'
    ports:
      - '5432:5432'
    volumes:
      - dbt_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: on-failure

volumes:
  dbt_pg_data:
    name: dbt_pg_data
