triggers:
- envs: []
  last_enabled_at: 2024-02-05 03:24:17.426048+00:00
  name: green_taxi_gcs_to_bigquery_schedule
  pipeline_uuid: green_taxi_gcs_to_bigquery
  schedule_interval: 0 5 * * *
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-02-05 00:00:00+00:00
  status: inactive
  variables: {}
