version: "3.9"

x-spark-image: &spark-image bitnami/spark:${BITNAMI_SPARK_VERSION:-3.5.0}
x-hive-image:  &hive-image  apache/hive:${HIVE_VERSION:-4.0.0-beta-1}

x-spark-common: &spark-common
  image: *spark-image
  restart: on-failure:3
  volumes:
    - ${SPARK_JARS:-}/:/opt/spark-jars/
    - ${GOOGLE_APPLICATION_CREDENTIALS:-}:/.gcp/gcp_credentials.json

x-spark-worker-common: &spark-worker-common
  <<: *spark-common
  environment:
    SPARK_MODE: 'worker'
    SPARK_MASTER_URL: 'spark://spark-master:7077'
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 4g
    SPARK_WORKER_WEBUI_PORT: 4040
  depends_on:
    - spark-master

services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    environment:
      SPARK_MODE: 'master'
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 4040
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4040:4040'

  spark-worker1:
    <<: *spark-worker-common
    container_name: spark-worker1
    ports:
      - '4041:4040'

  metastore:
    image: *hive-image
    container_name: metastore
    environment:
      SERVICE_NAME: 'metastore'
    ports:
      - '9083:9083'
    volumes:
      - hive_warehouse:/opt/hive/data/warehouse

  hiveserver:
    image: *hive-image
    container_name: hiveserver
    environment:
      SERVICE_NAME: 'hiveserver2'
      SERVICE_OPTS: '-Dhive.metastore.uris=thrift://metastore:9083'
      IS_RESUME: 'true'
    ports:
      - '10000:10000'
      - '10002:10002'
    depends_on:
      - metastore
    volumes:
      - hive_warehouse:/opt/hive/data/warehouse

volumes:
  hive_warehouse:
    name: hive_warehouse
