version: "3.9"

x-spark-image: &spark-image bitnami/spark:${BITNAMI_SPARK_VERSION:-3.5.0}

x-spark-common: &spark-common
  image: *spark-image
  environment: 
    &spark-common-env
    SPARK_RPC_AUTHENTICATION_ENABLED: 'no'
    SPARK_RPC_ENCRYPTION_ENABLED: 'no'
    SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: 'no'
    SPARK_SSL_ENABLED: 'no'
    SPARK_USER: 'spark'
  volumes:
    - ${SPARK_JARS:-}/:/opt/spark-jars/
    - ${GOOGLE_APPLICATION_CREDENTIALS:-}:/.gcp/gcp_credentials.json
  restart: on-failure

x-spark-worker-common: &spark-worker-common
  <<: *spark-common
  environment:
    <<: *spark-common-env
    SPARK_MODE: 'worker'
    SPARK_MASTER_URL: 'spark://spark-master:7077'
    SPARK_WORKER_MEMORY: '1G'
    SPARK_WORKER_CORES: 1
    SPARK_WORKER_WEBUI_PORT: 4040


services:
  spark-master:
    <<: *spark-common
    container_name: spark_master
    environment:
      SPARK_MODE: 'master'
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 4040
    ports:
      - '7077:7077'
      - '4040:4040'

  spark-worker1:
    <<: *spark-worker-common
    container_name: spark_worker
    ports:
      - '4041:4040'
