version: "3.9"
services:
  spark-master:
    container_name: spark-master
    image: bitnami/spark:3.5.0
    hostname: spark-master
    restart: on-failure
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=9090
      - SPARK_LOCAL_IP=spark-master
    ports:
      - '9090:9090'
      - '7077:7077'
    networks:
      - spark

  spark-worker-node1:
    container_name: spark-worker-node1
    image: bitnami/spark:3.5.0
    hostname: spark-worker-node1
    restart: on-failure
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=24g
      - SPARK_WORKER_WEBUI_PORT=9091
    ports:
      - '9191:9091'
    networks:
      - spark
    depends_on:
      - spark-master

  spark-worker-node2:
    container_name: spark-worker-node2
    image: bitnami/spark:3.5.0
    hostname: spark-worker-node2
    restart: on-failure
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=24g
      - SPARK_WORKER_WEBUI_PORT=9091
    ports:
      - '9291:9091'
    networks:
      - spark
    depends_on:
      - spark-master

networks:
  spark:
    name: spark-network