x-spark-image: &spark-image bitnami/spark:${BITNAMI_SPARK_VERSION:-3.5.0}

x-spark-common: &spark-common
  image: *spark-image
  restart: on-failure:3
  volumes:
    - ${SPARK_JARS:-}/:/opt/spark-jars/
    - ${GOOGLE_APPLICATION_CREDENTIALS:-}:/.gcp/gcp_credentials.json

x-spark-worker-common: &spark-worker-common
  <<: *spark-common
  environment:
    SPARK_MODE: 'worker'
    SPARK_MASTER_URL: 'spark://spark-master:7077'
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 4g
    SPARK_WORKER_WEBUI_PORT: 4040
  depends_on:
    - spark-master

version: "3.9"
services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    environment:
      SPARK_MODE: 'master'
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 4040
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4040:4040'

  spark-worker1:
    <<: *spark-worker-common
    container_name: spark-worker1
    ports:
      - '4041:4040'

  spark-worker2:
    <<: *spark-worker-common
    container_name: spark-worker2
    ports:
      - '4042:4040'
