version: 2

models:
  - name: dim_zone_lookup
    description: >
      List of unique zones idefied by locationid.
      Includes the service zone they correspond to (Green or yellow).

  - name: fact_yellow_green_trips
    description: >
      Taxi trips corresponding to both service zones (Green and yellow).
      The table contains records where both pickup and dropoff locations are valid and known zones.
      Each record corresponds to a trip uniquely identified by tripid.

  - name: dim_monthly_zone_revenue
    description: >
      Aggregated table of all taxi trips corresponding to both service zones (Green and yellow) per pickup zone, month and service.
      The table contains monthly sums of the fare elements used to calculate the monthly revenue.
      The table contains also monthly indicators like number of trips, and average trip distance.
    columns:
      - name: revenue_monthly_total_amount
        description: Monthly sum of the the total_amount of the fare charged for the trip per pickup zone, month and service.
        tests:
          - not_null:
              severity: error

metrics:
  - name: average_distance
    label: Average Distance
    model: ref('fact_yellow_green_trips')
    description: "The average trip distance"

    calculation_method: average
    expression: trip_distance

    timestamp: pickup_datetime
    time_grains: [month, quarter, year]

    tags:
    - piperider
