version: 2

sources:
  - name: pg-raw-nyc-trip_record
    database: "{{ env_var('DBT_POSTGRES_DATABASE') }}"
    schema: "{{ 'raw_' ~ env_var('DBT_POSTGRES_SCHEMA') }}"
    tables:
      - name: ntl_green_taxi
      - name: ntl_yellow_taxi
