name: 'dbt_duckdb_analytics'
version: '2.0.0'
config-version: 2

profile: 'duckdb-local'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directory which will store compiled SQL files
target-path: "target"  

# directories to be removed by `dbt clean`
clean-targets:         
  - "target"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_duckdb_analytics:
    staging:
      materialized: table
    core:
      materialized: table

vars:
  payment_type_values: [1, 2, 3, 4, 5, 6]
