[project]
name = ""
version = "1.0"
description = "Analytics Engineering with dbt and Redshift"
license = {text = "CC-BY-SA-4.0"}
readme = "README.md"
authors = [
    {name = "Bruno Oliveira", email = "bruno.ariev@gmail.com"},
]

requires-python = ">=3.10,<3.12"

dependencies = [
    "dbt-redshift>=1.7.3,<2.0",
    "awscli>=1.32.7",
]

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.1.8",
]

[tool.ruff]
line-length = 100