version: 2

sources:
  - name: nyc_tlc_trip_record_data_parquet
    meta:
      external_location: "read_parquet('gs://iobruno-lakehouse-raw/nyc_tlc_trip_record_data/{name}/*.parquet')"
    tables:
      - name: fhv
      - name: green_taxi
      - name: yellow_taxi

  - name: nyc_tlc_trip_record_data_csv
    meta:
      external_location: "read_csv('gs://iobruno-lakehouse-raw/nyc_tlc_trip_record_data/{name}/*.csv.gz', auto_detect=true)"
    tables:
      - name: zone_lookup
