version: 0.1.1
dev:
  ### PostgresSQL ### 
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_HOST: "{{ env_var('POSTGRES_HOST', 'host.docker.internal') }}"
  POSTGRES_PORT: "{{ env_var('POSTGRES_PORT', 5432) }}"
  POSTGRES_USER: "{{ env_var('POSTGRES_USER', 'postgres') }}"
  POSTGRES_PASSWORD: "{{ env_var('POSTGRES_PASSWORD', 'postgres') }}"
  POSTGRES_DBNAME: "{{ env_var('POSTGRES_DATABASE', 'postgres') }}"
  POSTGRES_SCHEMA: "{{ env_var('POSTGRES_DATABASE_SCHEMA', 'public') }}"

prod:
  ### PostgresSQL ### 
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_HOST: "{{ env_var('POSTGRES_HOST') }}"
  POSTGRES_PORT: "{{ env_var('POSTGRES_PORT', 5432) }}"
  POSTGRES_USER: "{{ env_var('POSTGRES_USER') }}"
  POSTGRES_PASSWORD: "{{ env_var('POSTGRES_PASSWORD') }}"
  POSTGRES_DBNAME: "{{ env_var('POSTGRES_DATABASE') }}"
  POSTGRES_SCHEMA: "{{ env_var('POSTGRES_DATABASE_SCHEMA') }}"
