version: "3.9"

x-clickhouse-image: &clickhouse-image clickhouse/clickhouse-server:${CLICKHOUSE_VERSION:-24-alpine}

services:
  clickhouse:
    image: *clickhouse-image
    container_name: clickhouse
    environment:
      CLICKHOUSE_DB: 'default'
      CLICKHOUSE_USER: 'clickhouse'
      CLICKHOUSE_PASSWORD: 'clickhouse'
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 0
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ch_data:/var/lib/clickhouse/
      - ch_logs:/var/log/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8123/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: on-failure

volumes:
  ch_data:
    name: clickhouse_data
  ch_logs:
    name: clickhouse_logs
