version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: on-failure:3
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'nyc_taxi'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: postgres_data
