[project]
name = "prefect-playground"
version = "1.0"
description = "Workflow orchestration with Prefect"
license = {text = "CC-BY-SA-4.0"}
readme = "README.md"
authors = [
    {name = "Bruno Oliveira", email = "bruno.ariev@gmail.com"},
]

requires-python = ">=3.12,<3.13"

dependencies = [
    "pandas>=2.2.3,<3.0",
    "pyarrow>=17.0.0,<18",
    "sqlalchemy>=2.0.35,<3.0",
    "psycopg[binary]>=3.2.3,<4.0",
    "prefect>=3.0.4,<4.0",
    "prefect-gcp>=0.6.1,<1.0",
    "prefect-sqlalchemy>=0.5.1,<1.0",
    "hydra-core>=1.3.2,<2.0",
]

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.6.9",
]

[tool.ruff]
line-length = 100
lint.select = ["F", "E", "W", "I001"]