x-postgres-image: &postgres-image postgres:${POSTGRES_VERSION:-16-alpine}
x-metabase-image: &metabase-image metabase/metabase:${METABASE_VERSION:-v0.50.12}

x-metabase-common: &metabase-common
  image: *metabase-image
  platform: linux/amd64
  user: "${MUID:-2000}:${MGID:-2000}"
  environment:
    MB_DB_TYPE: postgres
    MB_DB_HOST: metabase-db
    MB_DB_PORT: 5432
    MB_DB_DBNAME: metabase
    MB_DB_USER: metabase
    MB_DB_PASS: metabase
    MB_PLUGINS_DIR: ${MB_PLUGINS_DIR:-/app/plugins}
    MUID: ${MUID:-2000}
    MGID: ${MGID:-2000}
  volumes:
    - metabase_data:/metabase-data
    - metabase_plugins:${MB_PLUGINS_DIR:-/app/plugins}

services:
  metabase-db:
    image: *postgres-image
    container_name: metabase_db
    environment:
      POSTGRES_USER: 'metabase'
      POSTGRES_PASSWORD: 'metabase'
      POSTGRES_DB: 'metabase'
    ports:
      - '5432'
    volumes:
      - metabase_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: on-failure

  metabase:
    <<: *metabase-common
    container_name: metabase_app
    ports:
      - 3000:3000
    depends_on:
      metabase-db:
        condition: service_healthy
      metabase-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/api/health"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: on-failure

  metabase-init:
    <<: *metabase-common
    container_name: metabase_init
    user: "0:0"
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p $${MB_PLUGINS_DIR}
        curl -L -o $${MB_PLUGINS_DIR}/clickhouse.metabase-driver.jar https://github.com/ClickHouse/metabase-clickhouse-driver/releases/download/1.50.1/clickhouse.metabase-driver.jar
        chown -R $${MUID}:$${MGID} $${MB_PLUGINS_DIR}

volumes:
  metabase_pg_data:
    name: metabase_pg_data
  metabase_data:
    name: metabase_data
  metabase_plugins:
    name: metabase_plugins
