version: "3.9"

x-postgres-image: &postgres-image postgres:${POSTGRES_VERSION:-16-alpine}

services:
  postgres:
    image: *postgres-image
    container_name: postgres
    restart: on-failure:3
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'nyc_taxi'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: postgres_data
