version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: on-failure:5
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nyc_taxi
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - wk

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: on-failure:5
    hostname: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - "8080:80"
    networks:
      - wk

networks:
  wk:
    name: wk-orchestration