[project]
name = ""
version = "1.0"
description = "Workflow Orchestration playground with Prefect"
license = {text = "CC-BY-SA-4.0"}
readme = "README.md"
authors = [
    {name = "Bruno Oliveira", email = "bruno.ariev@gmail.com"},
]

requires-python = ">=3.10,<3.12"

dependencies = [
    "pandas>=2.1.3",
    "pyarrow>=14.0.1",
    "sqlalchemy>=1.4.50",
    "psycopg2-binary>=2.9.9",
    "prefect>=2.14.6",
    "prefect-gcp>=0.5.2",
    "prefect-sqlalchemy>=0.3.1",
    "omegaconf>=2.3.0",
]

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.1.6",
]

[tool.ruff]
line-length = 100