version: 2

sources:
  - name: bq-raw-nyc-trip_record
    database: "{{ env_var('DBT_BIGQUERY_PROJECT') }}"
    schema: "{{ 'raw_' ~ env_var('DBT_BIGQUERY_DATASET') }}"
    tables:
      - name: ext_fhv
      - name: ext_green
      - name: ext_yellow
