ny_taxi_tripdata@iobruno-gcp-labs:
  target: ny_taxi
  outputs:
    ny_taxi:
      type: bigquery
      project: iobruno-gcp-labs
      dataset: ny_taxi_staging
      location: us-central1
      threads: 4
      priority: interactive
      method: oauth
      job_execution_timeout_seconds: 300
      job_retries: 1
