x-postgres-image: &postgres-image postgres:${POSTGRES_VERSION:-16-alpine}

services:
  ingest-app:
    image: iobruno/pyingest:latest
    container_name: ingest-app
    build:
      dockerfile: ./Dockerfile
    environment:
      DATABASE_HOST: 'postgres'
      DATABASE_NAME: 'nyc_taxi'
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'postgres'
    volumes:
      - ./datasets.yml:/app/datasets.yml
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: *postgres-image
    container_name: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'nyc_taxi'
    ports:
      - '5432:5432'
    volumes:
      - ingest_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

volumes:
  ingest_pgdata:
    name: ingest_pgdata
