version: "3.9"

x-postgres-image: &postgres-image postgres:${POSTGRES_VERSION:-16-alpine}

services:
  ingest-app:
    image: iobruno/nyc-taxi-ingest:latest
    container_name: ingest-app
    environment:
      DATABASE_HOST: 'ingest-db'
      DATABASE_NAME: 'nyc_taxi'
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'postgres'
    volumes:
      - ./datasets.yml:/app/datasets.yml
    depends_on:
      ingest-db:
        condition: service_healthy

  ingest-db:
    image: *postgres-image
    container_name: ingest-db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'nyc_taxi'
    ports:
      - '5432:5432'
    volumes:
      - ingest_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

volumes:
  ingest_pgdata:
    name: ingest_pgdata
