[project]
name = ""
version = "1.0"
description = "CLI for retrieving NYC Taxi record dataTripdata and persisting it with SQLAlchemy and Pandas"
license = {text = "CC-BY-SA-4.0"}
readme = "README.md"
authors = [
    {name = "Bruno Oliveira", email = "bruno.ariev@gmail.com"},
]

requires-python = ">=3.10,<3.12"

dependencies = [
    "typer[all]>=0.9.0,<1.0",
    "pandas>=2.2.1,<3.0",
    "pyarrow>=15.0.0,<16",
    "polars>=0.20.13,<1.0",
    "adbc-driver-manager>=0.10.0,<1.0",
    "adbc-driver-postgresql>=0.10.0,<1.0",
    "sqlalchemy>=2.0.27,<3.0",
    # psycopg2 is required here for 'adbc' as it's not yet compatible yet with psycopg >= 3.0
    "psycopg2-binary>=2.9.9,<3.0",
    "omegaconf>=2.3.0,<3.0",
]

[tool.pdm.dev-dependencies]
dev = [
    "jupyterlab>=4.1.2",
    "ruff>=0.3.0",
]

[tool.ruff]
line-length = 100
select = ["F", "E", "W", "I001"]
