[project]
name = ""
version = "1.0"
description = "CLI for retrieving NYC Taxi record dataTripdata and persisting it with SQLAlchemy and Pandas"
license = {text = "CC-BY-SA-4.0"}
readme = "README.md"
authors = [
    {name = "Bruno Oliveira", email = "bruno.ariev@gmail.com"},
]

requires-python = ">=3.10,<3.12"

dependencies = [
    "typer[all]>=0.9.0,<1.0",
    "pandas>=2.1.3,<3.0",
    "polars>=0.20.5,<1.0",
    "pyarrow>=14.0.1,<15",
    "adbc-driver-manager>=0.9.0",
    "adbc-driver-postgresql>=0.9.0",
    "sqlalchemy>=2.0.23,<3.0",
    # psycopg2 is required here for 'adbc' as it's not yet compatible yet with psycopg >= 3.0
    "psycopg2-binary>=2.9.9,<3.0",
    "mysql-connector-python>=8.2.0,<9.0",
    "omegaconf>=2.3.0,<3.0",
]

[tool.pdm.dev-dependencies]
dev = [
    "jupyterlab>=4.0.9",
    "ruff>=0.1.6",
]

[tool.ruff]
line-length = 100
