[project]
name = ""
version = "1.0"
description = "data load tool workshop"
license = {text = "CC-BY-SA-4.0"}
readme = "README.md"
authors = [
    {name = "Bruno Oliveira", email = "bruno.ariev@gmail.com"},
]

requires-python = ">=3.10,<3.12"

dependencies = [
    "dlt[duckdb]>=0.4.4",
    "dlt[bigquery]>=0.4.4",
    "duckdb>=0.9.2,<1.0",
    "pandas>=2.2.0,<3.0",
    "pyarrow>=15.0.0",
    "google-cloud-bigquery-storage>=2.24.0,<3.0",
]

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.1.6",
    "jupyterlab>=4.1.1",
]

[tool.ruff]
line-length = 100
